### PR TITLE
Use a map to find the index of a level in O(1) time

### PR DESCRIPTION
**Pull request by lpinca**
This is fairly subjective and given the size of the array it is not really required.
Feel free to do whatever you want with this pr.

### CODE REVIEW

**Comment by lpinca** [comment]
```
console-log-level@1.2.0 x 1,485,526 ops/sec ±0.59% (95 runs sampled)
console-log-level#6b2040b x 1,639,820 ops/sec ±0.65% (89 runs sampled)
Fastest is console-log-level#6b2040b
```
In the best case (when using `log.fatal`) this is faster by 10% :smile:

**Comment by watson** [comment]
@lpinca I originally opted for the simpler, but marginally slower approach because the code is only running when the module is first initialised. I don't see a use-case where you'd like to create a lot of new loggers at runtime.

Unless I've misunderstood your PR, this only changes the startup time right? I think prefer the simpler and less clever code :wink:

**Comment by lpinca** [comment]
This patch does not improve the start time of the logger, it actually makes it slower.

This patch gets rid of [this loop](https://github.com/watson/console-log-level/blob/e9d09edc36fc51376d268421c646b5c4304fa4c7/index.js#L14) which is run every time you log something.
In the worst case this takes `O(n)` where `n` is the size of the array of levels.

**Comment by watson** [comment]
@lpinca Ah true - missed that.

Wouldn't a simpler approach be to just have all log-level functions below the treshold be a noop? This could easily be achieved by moving the `shouldLog` check outside the actual log function? Here is a quick and untested mockup based on the old code:

```js
  levels.forEach(function (level) {
    logger[level] = shouldLog(level) ? log : noop

    function log () {
      var prefix = opts.prefix
      var normalizedLevel

      switch (level) {
        case 'trace': normalizedLevel = 'info'; break
        case 'debug': normalizedLevel = 'info'; break
        case 'fatal': normalizedLevel = 'error'; break
        default: normalizedLevel = level
      }

      if (prefix) {
        if (typeof prefix === 'function') prefix = prefix()
        arguments[0] = util.format(prefix, arguments[0])
      }

      console[normalizedLevel].apply(console, arguments)
    }
  })
```

The `noop` function can just be defined in the top of the file: `var noop = function () {}`

That way the `shouldCheck` only runs on initialisation :smiley:

**Comment by lpinca** [comment]
Sounds good and a lot cleaner :+1:

**Comment by watson** [comment]
@lpinca do you want to make the change or should I?

**Comment by lpinca** [comment]
As you wish, I can probably do this this afternoon, but if you have time go ahead :)
Closing this.

**Pull request closed without merging**
